# Generated by Django 5.0.6 on 2024-05-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=256)),
                ('artist', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
            ],
        ),
    ]
