# Generated by Django 5.0.6 on 2024-05-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=256)),
                ('username', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default=None, upload_to='artist/images')),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('other', models.URLField(blank=True)),
            ],
        ),
    ]
